### ISSUE TITLE
os.getlogin problem

### ISSUE THREAD

**Issue by a2902793** [sleeepyjack/dockersh#7]
First time running `dockersh -t` after fresh install will give
```bash
Traceback (most recent call last): File "/usr/local/bin/dockersh", line 22, in <module> user = os.getlogin() FileNotFoundError: [Errno 2] No such file or directory
```
found a workaround from some other github issue and stackoverflow answer suggesting to replace os.getlogin in line 22 of dockersh to
```python
import pwd
import os

getlogin = lambda: pwd.getpwuid(os.getuid())[0]
user = getlogin()
```
this will only eliminate the error above and will ran into the issue #5 ...
any suggestions on how to make the whole dockersh working?

**Comment by tr4c3datr4il** [comment]
> First time running `dockersh -t` after fresh install will give
> 
> ```shell
> Traceback (most recent call last): File "/usr/local/bin/dockersh", line 22, in <module> user = os.getlogin() FileNotFoundError: [Errno 2] No such file or directory
> ```
> 
> found a workaround from some other github issue and stackoverflow answer suggesting to replace os.getlogin in line 22 of dockersh to
> 
> ```python
> import pwd
> import os
> 
> getlogin = lambda: pwd.getpwuid(os.getuid())[0]
> user = getlogin()
> ```
> 
> this will only eliminate the error above and will ran into the issue #5 ... any suggestions on how to make the whole dockersh working?

Hi, although today is 2023 now but it's never too late to do this:
`echo $UID > /proc/self/loginuid`
Use this command in your terminal :D
